# Stable version (90% traffic - 9 replicas)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-stable
spec:
  replicas: 9
  selector:
    matchLabels:
      app: aceest-canary
  template:
    metadata:
      labels:
        app: aceest-canary
        track: stable
    spec:
      containers:
      - name: aceest-fitness
        image: akshaya45/aceest-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
# Canary version (10% traffic - 1 replica)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest-canary
      track: canary
  template:
    metadata:
      labels:
        app: aceest-canary
        track: canary
    spec:
      containers:
      - name: aceest-fitness
        image: akshaya45/aceest-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
# Single service routes to both
apiVersion: v1
kind: Service
metadata:
  name: aceest-canary-service
spec:
  selector:
    app: aceest-canary
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30004